---
- name: Download Apache Maven from mirror site.
  get_url:
    dest: "{{ maven_download_dir }}/{{ maven_tarball }}"
    url: "{{ maven_mirror }}/{{ maven_tarball }}"
    checksum: "{{ maven_redis_checksum }}"
    owner: root
    group: root
    mode: "u=rwx,go=rx"
  register: maven_redis_get
  until: "'OK' in maven_redis_get.msg or 'file already exists' in maven_redis_get.msg"
  retries: 5
  delay: 5
  become: true

- name: Install Apache Maven
  unarchive:
    src: "{{ maven_download_dir }}/{{ maven_tarball }}"
    dest: "{{ maven_install_dir }}"
    owner: root
    group: root
    mode: "go-w"
  become: true

- name: Create symbolic link
  file:
    src: "{{ maven_install_dir }}/apache-maven-{{ maven_version }}"
    dest: "{{ maven_install_dir }}/maven"
    force: true
    state: link
  become: true
